
(defun sweyla713619 ()
  "Theme generated by Sweyla: http://themes.sweyla.com/seed/713619/"
  (interactive)
  (color-theme-install
   '(sweyla713619
     ((background-color . "#000B00")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#A87A65"))))
     (font-lock-constant-face ((t (:foreground "#FFFFFF"))))
     (font-lock-builtin-face ((t (:foreground "#9B79FF"))))
     (font-lock-function-name-face ((t (:foreground "#A4683A"))))
     (font-lock-variable-name-face ((t (:foreground "#FFFFCB"))))
     (font-lock-keyword-face ((t (:foreground "#59D5FA"))))
     (font-lock-string-face ((t (:foreground "#FF7FCA"))))
     (font-lock-doc-string-face ((t (:foreground "#FF7FCA"))))
     (font-lock-type-face ((t (:foreground "#B59EF7"))))
     )))

(provide 'sweyla713619)
