
(defun sweyla858470 ()
  "Theme generated by Sweyla: http://themes.sweyla.com/seed/858470/"
  (interactive)
  (color-theme-install
   '(sweyla858470
     ((background-color . "#000609")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#3F843F"))))
     (font-lock-constant-face ((t (:foreground "#575757"))))
     (font-lock-builtin-face ((t (:foreground "#D83849"))))
     (font-lock-function-name-face ((t (:foreground "#6F0095"))))
     (font-lock-variable-name-face ((t (:foreground "#6A0C79"))))
     (font-lock-keyword-face ((t (:foreground "#C71A1A"))))
     (font-lock-string-face ((t (:foreground "#4933A6"))))
     (font-lock-doc-string-face ((t (:foreground "#4933A6"))))
     (font-lock-type-face ((t (:foreground "#63575B"))))
     )))

(provide 'sweyla858470)
