
(defun sweyla822646 ()
  "Theme generated by Sweyla: http://themes.sweyla.com/seed/822646/"
  (interactive)
  (color-theme-install
   '(sweyla822646
     ((background-color . "#030100")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#67435F"))))
     (font-lock-constant-face ((t (:foreground "#8255CC"))))
     (font-lock-builtin-face ((t (:foreground "#000AFF"))))
     (font-lock-function-name-face ((t (:foreground "#D00C0C"))))
     (font-lock-variable-name-face ((t (:foreground "#00CBB7"))))
     (font-lock-keyword-face ((t (:foreground "#B75EFF"))))
     (font-lock-string-face ((t (:foreground "#49873F"))))
     (font-lock-doc-string-face ((t (:foreground "#49873F"))))
     (font-lock-type-face ((t (:foreground "#2235B1"))))
     )))

(provide 'sweyla822646)
