
(defun sweyla980673 ()
  "Theme generated by Sweyla: http://themes.sweyla.com/seed/980673/"
  (interactive)
  (color-theme-install
   '(sweyla980673
     ((background-color . "#110C00")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#ED80A7"))))
     (font-lock-constant-face ((t (:foreground "#B40C51"))))
     (font-lock-builtin-face ((t (:foreground "#B000F1"))))
     (font-lock-function-name-face ((t (:foreground "#FF130C"))))
     (font-lock-variable-name-face ((t (:foreground "#7CC886"))))
     (font-lock-keyword-face ((t (:foreground "#55009A"))))
     (font-lock-string-face ((t (:foreground "#D01030"))))
     (font-lock-doc-string-face ((t (:foreground "#D01030"))))
     (font-lock-type-face ((t (:foreground "#FF0C0C"))))
     )))

(provide 'sweyla980673)
