
(defun sweyla651375 ()
  "Theme generated by Sweyla: http://themes.sweyla.com/seed/651375/"
  (interactive)
  (color-theme-install
   '(sweyla651375
     ((background-color . "#000000")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#2F4B8D"))))
     (font-lock-constant-face ((t (:foreground "#73515E"))))
     (font-lock-builtin-face ((t (:foreground "#87920C"))))
     (font-lock-function-name-face ((t (:foreground "#0C4F92"))))
     (font-lock-variable-name-face ((t (:foreground "#0C6EB6"))))
     (font-lock-keyword-face ((t (:foreground "#008B86"))))
     (font-lock-string-face ((t (:foreground "#0091C3"))))
     (font-lock-doc-string-face ((t (:foreground "#0091C3"))))
     (font-lock-type-face ((t (:foreground "#00F65F"))))
     )))

(provide 'sweyla651375)
