
(defun sweyla763669 ()
  "Theme generated by Sweyla: http://themes.sweyla.com/seed/763669/"
  (interactive)
  (color-theme-install
   '(sweyla763669
     ((background-color . "#000000")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#C449FF"))))
     (font-lock-constant-face ((t (:foreground "#FFCCFF"))))
     (font-lock-builtin-face ((t (:foreground "#8EA1FF"))))
     (font-lock-function-name-face ((t (:foreground "#FF6393"))))
     (font-lock-variable-name-face ((t (:foreground "#FF5A63"))))
     (font-lock-keyword-face ((t (:foreground "#997AFF"))))
     (font-lock-string-face ((t (:foreground "#A1855A"))))
     (font-lock-doc-string-face ((t (:foreground "#A1855A"))))
     (font-lock-type-face ((t (:foreground "#FF930F"))))
     )))

(provide 'sweyla763669)
