
(defun sweyla830513 ()
  "Theme generated by Sweyla: http://themes.sweyla.com/seed/830513/"
  (interactive)
  (color-theme-install
   '(sweyla830513
     ((background-color . "#0A0101")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#4E8D39"))))
     (font-lock-constant-face ((t (:foreground "#DA707E"))))
     (font-lock-builtin-face ((t (:foreground "#48A1B8"))))
     (font-lock-function-name-face ((t (:foreground "#02C1FF"))))
     (font-lock-variable-name-face ((t (:foreground "#B83FC8"))))
     (font-lock-keyword-face ((t (:foreground "#C406FF"))))
     (font-lock-string-face ((t (:foreground "#B320BE"))))
     (font-lock-doc-string-face ((t (:foreground "#B320BE"))))
     (font-lock-type-face ((t (:foreground "#00A2BF"))))
     )))

(provide 'sweyla830513)
